name: dats
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.5.0
  intl: ^0.19.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  dart_flutter_team_lints: ^3.1.0

executables:
  dats:
  dats_diff:
